FROM python:3.4-alpine
ADD . /code
WORKDIR /code
EXPOSE 5000
RUN pip install -r requirements.txt
CMD ["python", "app.py"]
ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']ENV RUNNER_12_8=os.environ['RUNNER_12_8']
ENV RUNNER_11_8=os.environ['RUNNER_11_8']